version: "3.9"
services:
  web:
    container_name: "web"
    image: node
    volumes:
      - ./web:/app/js
    working_dir: /app/js
    command: npm run build
    ports:
      - "3000:5000"
  spring:
    container_name: "spring"
    image: gradle:6.8.3-jdk15
    volumes:
      - ./Spring-Gradle:/app/spring
    working_dir: /app/spring
    command: gradle bootRun
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
  db:
    container_name: "db"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456ok
      POSTGRES_DB: postgres
    expose:
      - "5432"
