version: "3.9"
services:
  web:
    container_name: "web"
    build: ./web
    ports:
      - "3000:5000"
  spring:
    container_name: "spring"
    build: ./Spring-Gradle
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
  db:
    container_name: "db"
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456ok
      POSTGRES_DB: postgres
    expose:
      - "5432"
