spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 123456ok

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  web:
    resources:
      static-locations: classpath:/